ALTER TABLE DISCOUNTACTIVITY ADD COLUMN LIMITMAXNUM INTEGER;
ALTER TABLE DISCOUNTACTIVITY ADD COLUMN ALLOWADDNUM INTEGER;

CREATE TABLE MEMBERJOINDISCOUNT (
	ID  BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	MEMBERID BIGINT NOT NULL,
	DISCOUNTID BIGINT NOT NULL,
	ADDTIME DATETIME NOT NULL,
	VALIDTIME DATETIME NOT NULL
)

ALTER TABLE WHEELYSMEMBER ADD COLUMN SOURCE VARCHAR(20);

CREATE TABLE OPERATION (
	OPKEY VARCHAR(200) NOT NULL,
	OPNUM INTEGER NOT NULL,
	REFUSED INTEGER NOT NULL,
	ADDTIME DATETIME NOT NULL,
	UPDATETIME DATETIME NOT NULL,
	VALIDTIME DATETIME NOT NULL,
	TAG VARCHAR(20) DEFAULT NULL,
	PRIMARY KEY (OPKEY)
)

CREATE TABLE MOBILEDYNAMICCODE (
	UKEY VARCHAR(200) NOT NULL,
	VERSION SMALLINT NOT NULL,
	TAG VARCHAR(20) NOT NULL,
	MOBILE VARCHAR(20) NOT NULL,
	LASTIP VARCHAR(20) DEFAULT NULL,
	CHECKPASS VARCHAR(20) NOT NULL,
	VALIDTIME DATETIME NOT NULL,
	MEMBERID BIGINT DEFAULT NULL,
	CHECKCOUNT SMALLINT NOT NULL,
	TOTALCHECK SMALLINT NOT NULL,
	SENDCOUNT SMALLINT NOT NULL,
	PRIMARY KEY (UKEY)
)
