CREATE TABLE `MEMBERORDERINFO` (
  `MEMBERID` bigint(20) NOT NULL,
  `REGSTERTIME` datetime DEFAULT NULL,
  `TRADENO` varchar(20) DEFAULT NULL,
  `FIRSTORDERTIME` datetime DEFAULT NULL,
  `FIRSTSHOPID` bigint(20) DEFAULT NULL,
  `LASTORDERTIME` datetime DEFAULT NULL,
  `ORDERNUM` int(99) DEFAULT NULL,
  `CREATETIME` datetime DEFAULT NULL,
  `UPDATETIME` datetime DEFAULT NULL,
  PRIMARY KEY (`MEMBERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MEMBERADDRESS` (
`ID`  int(11) NOT NULL ,
`MEMBERID`  int(11) NOT NULL ,
`SHOPID`  int(11) NOT NULL ,
`USERNAME`  varchar(255) NULL ,
`MOBILE`  varchar(255) NULL ,
`ADDRESS`  varchar(255) NULL ,
`DETAILADDRESS`  varchar(255) NULL ,
`TYPE`  varchar(255) NULL ,
`CREATETIME`  datetime NULL ,
`UPDATETIME`  datetime NULL ,
PRIMARY KEY (`ID`)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;