UPDATE MCHORDERDETAIL SET UNIT='包',DESCRIPTION='每个' WHERE ID='1';
UPDATE MCHORDERDETAIL SET UNIT='包',DESCRIPTION='每个a' WHERE ID='2';
UPDATE MCHORDERDETAIL SET UNIT='包',DESCRIPTION='每个b' WHERE ID='3';