insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',31,31,'添加商铺','_blank','Y','G','accountManager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',31,31,'店铺管理','_blank','Y','G','accountManager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',31,31,'商品管理','_blank','Y','G','accountManager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',31,31,'运营商报名管理','_blank','Y','G','accountManager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',31,31,'商家统计报表','_blank','Y','G','accountManager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',31,31,'店铺用户报表','_blank','Y','G','accountManager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',31,31,'品相统计报表','_blank','Y','G','accountManager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',31,31,'店铺补货报表','_blank','Y','G','accountManager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',31,31,'补货商品管理','_blank','Y','G','accountManager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',31,31,'补货订单管理','_blank','Y','G','accountManager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',31,31,'新闻资讯管理','_blank','Y','G','accountManager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',31,31,'BANNER设置','_blank','Y','G','accountManager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',31,31,'增加员工','_blank','Y','G','accountManager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',31,31,'员工管理','_blank','Y','G','accountManager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',33,33,'商家管理','mainFrame','Y','W','Manager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',34,34,'数据报表管理','mainFrame','Y','W','Manager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',35,35,'供销管理','mainFrame','Y','W','Manager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',36,36,'内容管理','mainFrame','Y','W','Manager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',37,37,'员工管理','mainFrame','Y','W','Manager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('setup',39,39,'设置','wmainFrame','Y','W','setmanager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin/city/showcityList.xhtml',3901,3901,'划分大区','_blank','Y','W','cityManage');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',3504,3504,'圣唐商品管理','_blank','Y','W','shengtangManager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin260',3505,3505,'香季商品管理','_blank','Y','W','xiangjiManager');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('refund',39,39,'订单管理','wmainFrame','Y','W','orderRefundManage');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin/orderrefund/showRefundList.xhtml',3901,3901,'退款订单','_blank','Y','W','orderRefund');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin/operator/actityDetails.xhtml',3603,3603,'活动申明','_blank','Y','G','actityAdd');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin/operator/showOperatorList.xhtml',3305,3305,'运营商活动申请','_blank','Y','G','operatorActityAdd');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin/activity/showDiscountList.xhtml',3803,3803,'优惠活动添加 ','_blank','Y','W','activity');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin/operator/operatorList.xhtml',3603,3603,'运营商管理 ','_blank','Y','W','operatorManage');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin/booking/showbookingList.xhtml',3604,3604,'店铺关停审核 ','_blank','Y','W','bookingManage');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin/notice/shownotice.xhtml',3605,3605,'通知管理 ','_blank','Y','W','noticeManage');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin/rule/showruleList.xhtml?supplierid=1',3506,3506,'圣唐物流规则 ','_blank','Y','W','shengtangRule');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin/rule/showruleList.xhtml?supplierid=2',3507,3507,'香季物流规则 ','_blank','Y','W','xiangjiRule');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('update',3307,3307,'修改','_blank','Y','W','updateShop');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('delate',3308,3308,'删除','_blank','Y','W','delateShop');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('pei',3309,3309,'配置','_blank','Y','W','peizhiShop');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('product',3310,3310,'商品','_blank','Y','W','productShop');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('banner',3311,3311,'设置banner','_blank','Y','W','bannerShop');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('user',3312,3312,'员工','_blank','Y','W','userShop');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin/report/reportByShopSummary.xhtml',3405,3405,'销售额统计报表','_blank','Y','W','summary');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin/orderManager/showAllOrder.xhtml',3903,3903,'全部订单','_blank','Y','W','allOrder');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('memberManage',41,41,'用户管理','wmainFrame','Y','W','memberManage');
insert into WEBMODULE(MODULEURL,MATCHORDER,MENUCODE,MENUTITLE, TARGET,DISPLAY,TAG,ROLENAMES)
VALUES ('admin/member/getAllMember.xhtml',4101,4101,'全部用户','_blank','Y','W','allMember');