
UPDATE MCHORDERDETAIL SET quantitiy=30,weight=2000,address='长宁' WHERE ID='1';
UPDATE MCHORDERDETAIL SET UNIT='包',DESCRIPTION='每个a' WHERE ID='2';
UPDATE MCHORDERDETAIL SET UNIT='包',DESCRIPTION='每个b' WHERE ID='3';
 UPDATE MCHORDER SET ACCEPTSTATUS='Y' where STATUS='accept';
