
insert into SUPPLIER(ID,SUPPNAME,SHOPID,MCHPRODUCTID,ORDERID)
VALUES (1,'SHENGTANG_COMPANY',1,1,1)
insert into SUPPLIER(ID,SUPPNAME,SHOPID,MCHPRODUCTID,ORDERID)
VALUES (2,'XIANGJI_COMPANY',1,1,1)
